### ISSUE TITLE
Connection diagram and devices used

### ISSUE THREAD

**Issue by moookino** [apollo80/wireless-klipper#2]
Can you share how connection is done? 
Do you've mcu's usb connected to esp and then Klipper via wifi or connection is different?

**Comment by apollo80** [comment]
Hi.
The connection scheme is quite simple.
Klipper is able to work with various terminal devices (ttyUSB* and etc.). Based on this, it is required to build two bridges: one on a machine with a Klipper, the other on an MCU.
On a machine with Klipper, you need to raise the `tty <-> WiFi` bridge, which is done using the "socat" program. On the MCU, the bridge is built using the Robin Wi-Fi module (ESP8266) and its firmware.
Thus, the connection scheme is as follows.
```
klipper <-> tty <-> socat <-> WiFi <-> robin WiFi module <-> RX/TX <-> MCU
```

Or are you interested in how to raise it all from scratch?

**Comment by moookino** [comment]
Thanks for explanation, that makes sense. Only missing part for me is how to flash MKS wifi module as it has no usb. Can you share the way how to do it?

**Comment by apollo80** [comment]
Hi.

The MKS Robin Wi Fi is essentially an ESP8266 performed by ESP12F. There are quite a lot of options and examples of firmware for ESP12F on the Internet.

I flashed through a USB -> RX/TX converter with 3.3v output power.

As one of the examples of ESP12F firmware, I can give the following links:
https://forum.micropython.org/viewtopic.php?t=7057
https://www.youtube.com/watch?v=R-FDJsuH_eE

For training, you can buy "WeMos D1 Mini Pro V3.0 NodeMcu" and experiment on it.
